Actualizaciones al readme y a algunos tutoriales
enflujo/programacion-creativa pull request #39
Opened 2021-02-02 21:19 UTC by anattolia

Agregué una guía breve de VSCODE que necesita más detalles (Juan, puedes revisar, por fa?)
Modifiqué un poco el archivo de git-github de Jeanniffer y agregué algunas explicaciones aquí y allá. 
¡Bienvenidas las modificaciones si creen que faltó algo!

2021-02-03 15:38 UTC, 1cgonza requested changes
@anattolia veo en este push que hay archivos de otra cosa:

`/robo/anattolia/www/...`

Creo que vas a tener que borrar esa carpeta `www/` y luego hacer commit y push. Luego crear el `.gitignore` para ignorar `www/` así no se nos cuelan estos archivos por acá.

Estos archivos se metieron en este commit: ed8a9de

2021-02-03 16:05 UTC, anattolia commented
@1cgonza  Borré todo lo que no tenía que ver, creo... ¿Me confirmas?
Perdón por las torpezas, aún me pierde y me enoja lo de las ramas y las actualizaciones, je. Prometo mejorar!!

2021-02-03 16:55 UTC, 1cgonza requested changes

2021-02-03 16:55 UTC, 1cgonza commented on tutoriales/vscode.md
> +Configuración: #TODO --> ¿Juan, una ayudita aquí? No logré recordar cómo configurarlo.
Van a el icono de engranaje en la esquino inferior izquierda y hacer click en "Settings":
Usando el buscador que aparece allí, buscar lo que aparece entre comillas a continuación y asignar los siguientes valores:
- "editor.formatOnSave": **chuleado**
- "editor.tabSize": 2
- "editor.wordWrapColumn": 120
- "eslint.packageManager": yarn
- "prettier.jsxSingleQuote": **chuleado**
- "prettier.singleQuote": **chuleado**

2021-02-03 16:58 UTC, 1cgonza commented
@anattolia no te preocupes, vas mejorando en esto de a pocos. Otra anotación es que revisar un PR tan lleno de cambios y sobre tantos archivos es engorroso. Veo que mientras voy revisando me aparece que estoy anotando cosas que están desactualizadas y son varias cosas al tiempo. Yo sé que odias las ramas, pero ojala pudieras crear una rama por cada cosa: 
1. Cambios al Readme
2. Git y Github
3. Herramientas
Etc.

Por ahora estoy intentando trabajar sobre este PR grande.

2021-02-03 16:59 UTC, 1cgonza commented
> @1cgonza Borré todo lo que no tenía que ver, creo... ¿Me confirmas?
> Perdón por las torpezas, aún me pierde y me enoja lo de las ramas y las actualizaciones, je. Prometo mejorar!!

Los borraste pero no veo que pusieras el `.gitignore`

2021-02-15 17:53 UTC, 1cgonza commented
@anattolia este pull lo podemos cerrar? creo que ya organizaste todo esto en otros PR.

2021-02-15 19:03 UTC, closed without merging

2021-02-15 19:04 UTC, anattolia commented
Listo, la cierro y abro una nueva  con las instrucciones para configurar VSC