ejercicio clima anattolia
enflujo/programacion-creativa pull request #58
Opened 2021-03-24 17:36 UTC by anattolia

Nuevo ejercicio

2021-03-24 18:11 UTC, 1cgonza requested changes
Va muy bien! aquí las cosas pequeñas + lo otro que te comenté en el Discord

2021-03-24 18:11 UTC, 1cgonza commented on ejercicios/clima/anattolia/src/programa.js
> +  let img = 1;
Ya tienes en el "scope" global una variable que se llama `img` mejor cambiar esto a otra cosa, puede ser `estadoImg`

2021-03-24 18:11 UTC, 1cgonza commented on ejercicios/clima/anattolia/src/programa.js
> +          pixeles[i] = pixeles[i];
No tienes que asignar el mismo valor a si mismo, puedes borrar esta linea y te ahorras un montón de recursos.

2021-03-30 15:26 UTC, 1cgonza requested changes
@anattolia te señalo donde esta el problema. Con ese cambio ya queda bien para subirlo

2021-03-30 15:26 UTC, 1cgonza commented on ejercicios/clima/anattolia/src/programa.js
>      if (pixeles.length) {
En este punto los pixeles pueden no estar cargados ya que `onclick` se ejecuta inmediatamente mientras que `img.onload` en la linea 56 es asincrónico. En tu compu de manera local puede que funcione porque la imagen carga rápido, pero en un servidor no va a funcionar. Tienes que esperar a que los pixeles estén listos antes de procesarlos. Es posible que este bloque:

```js
datosImagen = ctx.getImageData(0, 0, window.innerWidth, window.innerHeight);
 // Sacar los pixeles que es un Array y cada color tiene 4 valores [r, g, b, a, r, g, b, a, ....];
 pixeles = datosImagen.data;
``` 
Te toque moverlo a otro lado donde sepas que la imagen seguro esta cargada.

2021-03-31 05:46 UTC, 1cgonza requested changes
Otro problema es que los colores de la imagen no cambian de vuelta pero es porque se te olvido cambiarle el nombre de la variable a la que te propuse

Ahora tienes 

```js
} else if (img === 0) {
```
Pero debería ser:
```js
} else if (estadoImg === 0) {
```

2021-03-31 05:46 UTC, 1cgonza commented on ejercicios/clima/anattolia/src/programa.js
> +    click();
El problema no es cuando se asigna el `click` sino cuando se extraen los pixeles.

Lo que debes hacer es extraer los pixeles cuando la imagen esta cargada:

```js
function pintar(datos) {
  img.src = datos.img;
  img.onload = () => {
    imprimirImg();
    imprimirCoor(datos.color);
    imprimirTxt(datos.fuente, datos.p1, datos.p2);
    creditos.innerHTML = datos.creditos;
    document.body.style.backgroundColor = datos.fondo;
    //--- AQUÍ YA SE PUEDEN EXTRAER LOS PIXELES PORQUE LO HACES DESPUES DE onload --
    datosImagen = ctx.getImageData(0, 0, window.innerWidth, window.innerHeight);
    // Sacar los pixeles que es un Array y cada color tiene 4 valores [r, g, b, a, r, g, b, a, ....];
    pixeles = datosImagen.data;
    click();
  };
}
```

2021-04-01 01:34 UTC, anattolia commented on ejercicios/clima/anattolia/src/programa.js
> +    click();
¿Por qué si
```
pixeles = datosImagen.data;
click();
```
lo pongo al final de `async function obtenerClima(lat, lon)` no es la misma idea? ¿Estoy esperando a que ejecute alguno de los pintar() para luego obtener los datos de los pixeles o lo que está fuera de los if/else/else if se ejecuta primero aunque esté al final?

2021-04-02 15:53 UTC, anattolia commented on ejercicios/clima/anattolia/src/programa.js
> +    click();
@1cgonza cambié de lugar el ctx.getImageData

2021-04-06 16:36 UTC, 1cgonza commented on ejercicios/clima/anattolia/src/programa.js
> +    click();
Tienes 2 eventos asincrónicos, uno es el llamado al api y el segundo es el de `img.onload` entonces, a pesar de que el segundo este dentro del `async` este sólo esta esperando al llamado del API y no a que cargue la imagen. ¿se entiende?

2021-04-07 03:29 UTC, anattolia commented on ejercicios/clima/anattolia/src/programa.js
> +    click();
Ok. 
¿Ahora que el ctx.getImageData está dentro del img.onload() ya está bien?

2021-04-19 21:34 UTC, 1cgonza requested changes
Un par de detalles para terminar.

2021-04-19 21:34 UTC, 1cgonza commented on ejercicios/clima/anattolia/src/programa.js
>      obtenerClima(lat, lon);
Esta función ya no recibe parámetros entonces puedes llamarla simplemente con: `obtenerClima();`

2021-04-19 21:34 UTC, 1cgonza commented on ejercicios/clima/anattolia/src/programa.js
> +  datosImagen2 = ctx2.getImageData(0, 0, window.innerWidth, window.innerHeight);
Esta extracción de datos es pesada y no la necesitas.

2021-04-19 21:34 UTC, 1cgonza commented on ejercicios/clima/anattolia/src/programa.js
> +      ctx.putImageData(datosImagen2, 0, 0);
Ya que tienes la imagen en el otro canvas, lo puedes pintar acá simplemente con `ctx.drawImage(...)` eso te ahorra la extracción de pixeles en la linea 224.

2021-04-19 21:38 UTC, 1cgonza requested changes
Otro problema...

2021-04-19 21:38 UTC, 1cgonza commented on ejercicios/clima/anattolia/src/programa.js
> +      if (!imgTransformada) {
Viendo esto bien, falta cambiar este boolean después de transformar los pixeles.... al final debe pasar a 

```js
imgTransformada = true;
```

De lo contrario siempre va a ser `false` y siempre hace la conversión de pixeles.

2021-04-22 13:30 UTC, anattolia commented on ejercicios/clima/anattolia/src/programa.js
> +      ctx.putImageData(datosImagen2, 0, 0);
El problema al reemplazar `ctx.putImageData(datosImagen2, 0, 0);` por `ctx.drawImage(...)` es que solo me muestra la imagen pero no los textos. Tendría que volver a llamar la función "dibujar" para obtener los datos, ¿no?

2021-04-22 13:47 UTC, 1cgonza commented on ejercicios/clima/anattolia/src/programa.js
> +      ctx.putImageData(datosImagen2, 0, 0);
Es verdad, pero es más rápido pintar el segundo canvas en el que esta en la pantalla y luego pintar los textos. Lo que puedes hacer es separar la pintada de los textos en una función y ejecutarla después de pintar en cada momento que necesitas. Lo que es muy pesado es repetir el `getImageData`

2021-04-23 15:34 UTC, anattolia commented on ejercicios/clima/anattolia/src/programa.js
> +      ctx.putImageData(datosImagen2, 0, 0);
@1cgonza Creo que ahora sí

2021-05-02 17:15 UTC, merged